# Generated by Django 5.0.3 on 2024-06-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QurilishTashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('hudud', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='QuriishBinosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maydoni', models.CharField(max_length=255)),
                ('qavat', models.IntegerField()),
                ('parkovka', models.BooleanField(default=True)),
                ('bolalar_maydonchasi', models.BooleanField(default=True)),
                ('lift', models.BooleanField(default=True)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hudud')),
                ('qurilish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qurilishtashkiloti')),
            ],
        ),
    ]
